name: Windows Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest

    permissions:
          contents: write # REQUIRED for releases

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg

      # ---------------- Cache vcpkg packages ----------------
      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/vcpkg/packages
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      # ---------------- Manifest Mode ----------------
      - name: Install dependencies via vcpkg (manifest mode)
        run: |
          ${{ github.workspace }}/vcpkg/vcpkg install

      - name: Configure CMake
        run: |
          cmake -S . -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake `
            -DUSE_FAISS=ON

      - name: Build
        run: |
          cmake --build build --config Release --parallel

      - name: Collect runtime DLLs
        shell: pwsh
        run: |
          mkdir runtime
          copy build/Release/embedding_engine.exe runtime/
          copy vcpkg/installed/x64-windows/bin/*.dll runtime/

      - name: Zip bundle
        run: |
          Compress-Archive -Path runtime/* -DestinationPath embedding_engine_windows.zip

      # - name: Upload executable
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: embedding_engine_windows
      #     path: build/Release/embedding_engine.exe


      # ---------------- Upload to GitHub Release ----------------
      # - name: Upload EXE to GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: build/Release/embedding_engine.exe
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: embedding_engine_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
